apiVersion: v1
kind: Service
metadata:
  name: {{ app.name }}-backend
  namespace: {{ namespace }}
  labels:
    app: {{ app.name }}
    component: backend
spec:
  type: ClusterIP
  selector:
    app: {{ app.name }}
    component: backend
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
